file_paths:
    input_calibrant_file: ../../../SXRD_raw_data/diamond_2021/rawdata_tiffs/103853_tiffs/00001_00000.tiff
    # Input file path for the calibrant diffraction pattern image
    
    output_calibration_path: ../../../SXRD_analysis/diamond_2021/103853-calibration/calibration-pyFAI/calibration_103853_CeO2_907mm_pyFAI.poni
    # Output file path for the .poni calibration file
    
    input_path: ../../../SXRD_analysis/diamond_2021/
    # Input file path for the diffraction pattern images
    
    input_experiment_list: 
    - 103828/texture-cpf
    - 103829/texture-cpf
    - 103830/texture-cpf
    - 103831/texture-cpf
    - 103832/texture-cpf
    - 103833/texture-cpf
    - 103834/texture-cpf
    - 103835/texture-cpf
    - 103836/texture-cpf
    - 103837/texture-cpf
    - 103838/texture-cpf
    - 103839/texture-cpf
    # Input experiment list (name of input folders)
    
    glob_search_term: 1*.tiff
    # Glob search term (common name of the image files)
    
    output_path: ../../../SXRD_analysis/diamond_2021/
    # Output path for azimuthally integrated or caked data files
    
    output_experiment_list:
    - 103828
    - 103829
    - 103830
    - 103831
    - 103832
    - 103833
    - 103834
    - 103835
    - 103836
    - 103837
    - 103838
    - 103839
    # Output experiment list (name of output folders)
    
setup_inputs: 
    beam_centre_x: 755.767 
    # x-coordinate of the beam-centre in pixels
    
    beam_centre_y: 680.876
    # y-coordinate of the beam-centre in pixels
    # Note, this is 1679 - 998.124 since value from Dioptas is from top rather than bottom
    
    sample_detector_distance: 907.3740 
    # Sample-to-detector distance in millimetres (unit used by Fit2d)
   
    wl: 1.242000e-11 
    # Beam wavelength in metres

    pixel_x: 0.000172 
    # Pixel size in metres (in x)
    pixel_y: 0.000172 
    # Pixel size in metres (in y)

    calibrant_type: CeO2 
    # Calibrant type, eg. CeO2, LaB6, etc.
    
    num_calibration_rings: 15 
    # Number of calibrant rings used for calibration
    
refinement_inputs:
    number_of_points: 10000
    # Number of points used to resolve the intensity profile
    
    number_of_cakes: 72
    # Number of cakes for 'caking' the synchrotron diffraction pattern images
    
    pixel_size: 0.172
    # Pixel size in millimetres
    

