file_paths:
    input_calibrant_file: ../../../SXRD_raw_data/diamond_2021_fast_detector/rawdata/108835-pilatus2M-files/00001.tif
    # Input file path for the calibrant diffraction pattern image
    
    output_calibration_path: ../../../SXRD_analysis/diamond_2021_fast_detector/108835-calibration/calibration-pyFAI/Diamond_2021_Fast_Detector_CeO2_750mm_pyFAI.poni
    # Output file path for the .poni calibration file
    
    input_path: ../../../SXRD_raw_data/diamond_2021_fast_detector/rawdata/
    # Input file path for the diffraction pattern images
    
    input_experiment_list: 
    - 108849-pilatus2M-files/
    # Input experiment list (name of input folders)
    
    glob_search_term: 0*.tif
    # Glob search term (common name of the image files)
    
    output_path: ../../../SXRD_analysis/diamond_2021_fast_detector/
    # Output path for azimuthally integrated or caked data files
    
    output_experiment_list:
    - 108849-heating
    # Output experiment list (name of output folders)
    
setup_inputs: 
    beam_centre_x: 730.905
    # x-coordinate of the beam-centre in pixels
    
    beam_centre_y: 627.474
    # y-coordinate of the beam-centre in pixels
    
    sample_detector_distance: 741.189 
    # Sample-to-detector distance in millimetres (unit used by Fit2d)
   
    wl: 1.386600e-11 
    # Beam wavelength in metres

    pixel_x: 0.000172 
    # Pixel size in metres (in x)
    pixel_y: 0.000172 
    # Pixel size in metres (in y)

    calibrant_type: CeO2 
    # Calibrant type, eg. CeO2, LaB6, etc.
    
    num_calibration_rings: 10
    # Number of calibrant rings used for calibration
    
refinement_inputs: 
    number_of_points: 5000
    # Number of points used to resolve the intensity profile
    
    number_of_cakes: 72
    # Number of cakes for 'caking' the synchrotron diffraction pattern images
    
    pixel_size: 0.172
    # Pixel size in millimetres